import {useEffect,useState} from 'react';
import type {User} from '@supabase/supabase-js';
import {cloud} from './cloud';
import type {Locale} from './model';
const texts={
 pt:{title:'Sua conta',setup:'A conexão com sua conta ainda está sendo preparada. Seus cards continuam salvos neste navegador.',email:'E-mail',password:'Senha',login:'Entrar',logout:'Sair da conta',wait:'Aguarde…',error:'Não foi possível entrar. Confira seus dados e sua conexão.',logoutError:'Não foi possível sair. Tente novamente.',local:'Conta conectada. Use Sincronizar agora para enviar e recuperar sua biblioteca.',note:'Use a conta pessoal cadastrada para o Brains. Não há cadastro público.',exit:'Sair da conta mantém os cards neste aparelho.'},
 en:{title:'Your account',setup:'Your account connection is being prepared. Cards remain in this browser.',email:'Email',password:'Password',login:'Sign in',logout:'Sign out',wait:'Please wait…',error:'Unable to sign in. Check your details and connection.',logoutError:'Unable to sign out. Try again.',local:'Account connected. Use Sync now to send and retrieve your library.',note:'Use your personal Brains account. Public sign-up is not available.',exit:'Signing out keeps cards on this device.'},
 es:{title:'Tu cuenta',setup:'La conexión con tu cuenta se está preparando. Las tarjetas siguen en este navegador.',email:'Correo',password:'Contraseña',login:'Entrar',logout:'Salir',wait:'Espera…',error:'No se pudo entrar. Comprueba tus datos y conexión.',logoutError:'No se pudo salir. Inténtalo de nuevo.',local:'Cuenta conectada. Usa Sincronizar ahora para enviar y recuperar tu biblioteca.',note:'Usa tu cuenta personal de Brains. No hay registro público.',exit:'Salir mantiene las tarjetas en este dispositivo.'}
};
export function AccountPanel({locale,loginOnly=false}:{locale:Locale;loginOnly?:boolean}){
 const t=texts[locale];const [user,setUser]=useState<User|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(!!cloud),[error,setError]=useState('');
 useEffect(()=>{if(!cloud)return;let live=true;const {data}=cloud.auth.onAuthStateChange((_event,session)=>{if(live){setUser(session?.user??null);setLoading(false);setPassword('')}});void cloud.auth.getSession().then(({data,error})=>{if(live){setUser(data.session?.user??null);setLoading(false);if(error)setError('error')}}).catch(()=>{if(live){setLoading(false);setError('error')}});return()=>{live=false;data.subscription.unsubscribe()}},[]);
 return <section className="panel spaced">{!loginOnly&&<h2>{t.title}</h2>}{!cloud?<p>{t.setup}</p>:loading?<p role="status">{t.wait}</p>:user?<><p>{user.email}</p><p className="small">{t.local}</p><p className="small">{t.exit}</p><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const {error}=await cloud!.auth.signOut({scope:'local'});if(error)throw error;setUser(null)}catch{setError('logoutError')}finally{setBusy(false)}}}>{busy?t.wait:t.logout}</button></>:<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const {data,error}=await cloud!.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setUser(data.user)}catch{setError('error')}finally{setPassword('');setBusy(false)}}}><p className="small">{t.note}</p><label htmlFor="account-email">{t.email}</label><input id="account-email" type="email" autoComplete="username" value={email} required disabled={busy} onChange={e=>setEmail(e.target.value)}/><label htmlFor="account-password">{t.password}</label><input id="account-password" type="password" autoComplete="current-password" value={password} required disabled={busy} onChange={e=>setPassword(e.target.value)}/><button className="primary spaced" disabled={busy}>{busy?t.wait:t.login}</button></form>}{error&&<p role="alert">{error==='logoutError'?t.logoutError:t.error}</p>}</section>
}

