import {CloudStatus} from './CloudStatus';
import {cancelSpeech} from './voice';
import {AccountPanel} from './AccountPanel';

import {reviewQueue,applyReview} from './scheduler';
import {cardSide,dailyProgress} from './review';
import {useCallback,useEffect,useState} from 'react';
import {blankCard,languages,type Area,type Card,type Deck,type Draft,type Library,type Locale} from './model';
import {useStore} from './StoreContext';
import {translator,errorText,type T} from './i18n';
import {Editor} from './Editor';
import {SideView} from './Media';
import {Dialog} from './Dialog';
type Page='home'|'decks'|'area'|'editor'|'settings'|'explore';
type ChangeDialog={kind:'purge';id:string;type:'areas'|'cards'}|{kind:'area'|'deck';item?:Area|Deck}|{kind:'delete';type:'areas'|'decks'|'cards';id:string};
export default function App(){
 const store=useStore();
 const [now,setNow]=useState(()=>new Date());useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(timer)},[]);const [data,setData]=useState<Library|null>(null);const [drafts,setDrafts]=useState<Draft[]>([]);const [page,setPage]=useState<Page>('home');const [areaId,setAreaId]=useState('');const [draft,setDraft]=useState<Draft|null>(null);const [tab,setTab]=useState<'active'|'archived'|'trash'>('active');const [search,setSearch]=useState('');const [error,setError]=useState('');const [toast,setToast]=useState('');const [dialog,setDialog]=useState<ChangeDialog|null>(null);const [busy,setBusy]=useState(false);const [explore,setExplore]=useState<Card[]>([]);const [index,setIndex]=useState(0);const [back,setBack]=useState(false);const [known,setKnown]=useState(true);const [sessionId,setSessionId]=useState(()=>crypto.randomUUID());const t=translator(data?.preferences.locale??'pt');
 const refresh=useCallback(async()=>{try{const library=await store.read();const savedDrafts=await store.drafts();setData(previous=>previous&&previous.revision>library.revision?previous:library);setDrafts(savedDrafts.filter(d=>library.decks.some(parent=>parent.id===d.card.deckId)));setError('')}catch(e){setError(errorText(e,translator('pt')))}},[store]);
 useEffect(()=>{void refresh()},[refresh]);useEffect(()=>{document.documentElement.lang=data?.preferences.locale==='pt'?'pt-BR':data?.preferences.locale??'pt'},[data?.preferences.locale]);useEffect(()=>{if(!toast)return;const timeout=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timeout)},[toast]);
 useEffect(()=>{if(busy||dialog||!['home','decks','area'].includes(page))return;const reload=()=>{if(document.visibilityState==='visible')void refresh()};const timer=setInterval(reload,15000);window.addEventListener('focus',reload);window.addEventListener('online',reload);document.addEventListener('visibilitychange',reload);return()=>{clearInterval(timer);window.removeEventListener('focus',reload);window.removeEventListener('online',reload);document.removeEventListener('visibilitychange',reload)}},[page,busy,dialog,refresh]);
 const navigate=(next:Page)=>{cancelSpeech();setPage(next);setError('');setSearch('');window.scrollTo(0,0)};
 async function mutate(fn:(library:Library)=>void){if(!data)return false;setBusy(true);try{const updated=await store.mutate(data.revision,fn);setData(updated);setError('');return true}catch(e){setError(errorText(e,t));return false}finally{setBusy(false)}}
 async function edit(card:Card){const existing=drafts.find(d=>d.card.id===card.id);const next=existing??{id:crypto.randomUUID(),card,baseVersion:card.version,revision:0,savedAt:new Date().toISOString()};setBusy(true);try{const saved=existing??next;setDraft(saved);setDrafts(await store.drafts());navigate('editor')}catch(e){setError(errorText(e,t))}finally{setBusy(false)}}
 const activeDeck=(id:string)=>!!data?.decks.some(d=>d.id===id&&!d.deleted&&!d.archived&&data.areas.some(a=>a.id===d.areaId&&!a.deleted&&!a.archived));
 const setState=async(type:'areas'|'decks'|'cards',id:string,field:'archived'|'deleted',value:boolean)=>{await mutate(db=>{const item=db[type].find(i=>i.id===id);if(!item)return;item[field]=value;if(type==='cards'){const card=item as Card;card.version++;card.updatedAt=new Date().toISOString()}})};
 if(!data)return <main className="main standalone"><h1>Brains</h1><p role="status">{error||t('loading')}</p>{error&&<button className="primary" onClick={()=>void refresh()}>{t('retry')}</button>}{error&&<AccountPanel locale='pt'/>}</main>;
 const area=data.areas.find(a=>a.id===areaId);const areaDecks=data.decks.filter(d=>d.areaId===areaId);const progress=dailyProgress(data,now);const activeCards=data.areas.flatMap(a=>reviewQueue(data,now,a.id));const matchState=(item:{deleted:boolean;archived:boolean})=>tab==='trash'?item.deleted:tab==='archived'?!item.deleted&&item.archived:!item.deleted&&!item.archived;
 const formatDue=(date:Date|string)=>new Intl.DateTimeFormat(data.preferences.locale,{timeZone:data.preferences.timezone,day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(date));
 function reviewState(id:string){if(reviewQueue(data!,now,id).length)return null;const cards=data!.cards.filter(c=>!c.deleted&&!c.archived&&data!.decks.some(d=>d.id===c.deckId&&d.areaId===id&&!d.archived&&!d.deleted));const due=cards.filter(c=>c.memory).map(c=>new Date(c.memory!.due)).sort((a,b)=>+a-+b)[0];return <p className="review-state">{cards.length===0?t('addFirst'): <>{t('noDue')}{due&&<> · {t('nextReview')}: <time dateTime={due.toISOString()}>{formatDue(due)}</time></>}{cards.some(c=>!c.memory)&&<> · {t('newLimitReached')}</>}</>}</p>}
 const navigation=<>{(['home','decks','settings'] as const).map((p,i)=><button key={p} aria-current={(page===p||(p==='decks'&&['area','explore','editor'].includes(page)))?'page':undefined} disabled={page==='editor'} onClick={()=>{setTab('active');navigate(p)}} className={`nav ${page===p?'active':''}`}><span aria-hidden="true">{['◫','▤','⚙'][i]}</span>{t(['today','decks','settings'][i] as 'today')}</button>)}</>;
 const filters=<div className="tabs" role="group" aria-label={t('collection')}>{(['active','archived','trash'] as const).map(value=><button aria-pressed={tab===value} className={tab===value?'selected':''} key={value} onClick={()=>setTab(value)}>{t(value)}</button>)}</div>;
 function controls(type:'areas'|'decks'|'cards',item:Area|Deck|Card){return <div className="item-actions">{item.deleted?<><button className="text-btn" disabled={busy} onClick={()=>void setState(type,item.id,'deleted',false)}>{t('restore')}</button>{(type==='cards'||type==='areas')&&<button className="text-btn danger" disabled={busy} onClick={()=>setDialog({kind:'purge',id:item.id,type:type as 'areas'|'cards'})}>{t('deleteForever')}</button>}</>:<><button className="text-btn" disabled={busy} onClick={()=>void setState(type,item.id,'archived',!item.archived)}>{t(item.archived?'restore':'archive')}</button><button className="text-btn danger" disabled={busy} onClick={()=>setDialog({kind:'delete',type,id:item.id})}>{t('remove')}</button></>}</div>}
 return <div className="shell"><aside className="side"><div className="brand"><span className="mark">B</span>Brains</div><nav>{navigation}</nav></aside><main className="main"><header className="top"><div className="brand"><span className="mark">B</span>Brains</div></header>{page!=='settings'&&<CloudStatus compact t={t}/>} {error&&<div className="error" role="alert">{error}<button className="text-btn" onClick={()=>void refresh()}>{t('reload')}</button></div>}
 {(page==='home'||page==='decks')&&<>{page==='home'?<><p className="small">{new Date().toLocaleDateString(data.preferences.locale,{day:'numeric',month:'long'})}</p><h1>{t('title')}</h1><p className="muted">{t('subtitle')}</p><div className="hero"><span>{t('goal')}</span><div className="row"><strong>{progress.cards}<span className="goal-total"> / {data.preferences.goal}</span></strong><span>{t('studied')}</span></div><div className="track"><div className="fill" style={{width:Math.min(100,progress.cards/data.preferences.goal*100)+'%'}}/></div><div className="row"><span>{progress.attempts} {t('attempts')}</span><span>{progress.cards>=data.preferences.goal?t('goalReached'):Math.max(0,data.preferences.goal-progress.cards)+' '+t('remaining')}</span></div></div></>:<h1>{t('decks')}</h1>}{drafts.length>0&&<div className="notice"><h2>{t('drafts')}</h2>{drafts.map(d=><div className="row" key={d.id}><span>{d.card.front.text||t('untitled')}</span><button className="text-btn" onClick={()=>{setDraft(d);navigate('editor')}}>{t('resume')} →</button></div>)}</div>}<div className="section row"><h2>{t('areas')}</h2><button className="text-btn" onClick={()=>setDialog({kind:'area'})}>+ {t('newArea')}</button></div>{filters}<div className="grid">{data.areas.filter(matchState).map(a=><section className="tile" key={a.id}><button className="tile-open" onClick={()=>{setAreaId(a.id);setTab('active');navigate('area')}}><div className="flag" aria-hidden="true">▤</div><h2>{a.name}</h2><span className="small">{(()=>{const count=data.cards.filter(c=>!c.deleted&&data.decks.some(d=>d.id===c.deckId&&d.areaId===a.id)).length;return count+' '+t(count===1?'cardSingular':'cards')})()} →</span></button>{!a.deleted&&!a.archived&&<div className="area-actions"><button className="secondary" onClick={()=>{setAreaId(a.id);setTab('active');navigate('area')}}>{t('openDecks')}</button><button className="primary" disabled={!activeCards.some(c=>data.decks.some(d=>d.id===c.deckId&&d.areaId===a.id))} onClick={()=>{setAreaId(a.id);setExplore(reviewQueue(data,new Date(),a.id));setSessionId(crypto.randomUUID());setIndex(0);setBack(false);navigate('explore')}}>{t('review')} →</button></div>}{!a.deleted&&!a.archived&&reviewState(a.id)}<details><summary>{t('manage')}</summary>{!a.deleted&&<button className="text-btn" onClick={()=>setDialog({kind:'area',item:a})}>{t('rename')}</button>}{controls('areas',a)}</details></section>)}</div>{!data.areas.filter(matchState).length&&<div className="empty"><h2>{t(tab==='active'?'empty':'emptyTrash')}</h2>{tab==='active'&&<><p>{t('emptyHelp')}</p><button className="primary" onClick={()=>setDialog({kind:'area'})}>+ {t('newArea')}</button></>}</div>}</>}
 {page==='area'&&area&&<><button className="back" onClick={()=>{setTab('active');navigate('decks')}}>← {t('back')}</button><div className="row"><h1>{area.name}</h1></div>{!area.deleted&&!area.archived&&<div className="area-actions"><button className="primary" disabled={busy} onClick={()=>{const parent=areaDecks[0];if(parent)void edit(blankCard(parent))}}>+ {t('add')}</button><button className="secondary" disabled={!activeCards.some(c=>areaDecks.some(d=>d.id===c.deckId))} onClick={()=>{setExplore(reviewQueue(data,new Date(),areaId));setSessionId(crypto.randomUUID());setIndex(0);setBack(false);navigate('explore')}}>{t('review')} →</button></div>}{!area.deleted&&!area.archived&&reviewState(area.id)}{(area.deleted||area.archived)&&<p className="notice">{t('archivedParent')}</p>}{filters}<input aria-label={t('search')} placeholder={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/><div className="list">{data.cards.filter(c=>areaDecks.some(d=>d.id===c.deckId)&&matchState(c)&&(c.front.text+' '+c.back.text).toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(c=><section className="entry" key={c.id}><h2>{c.front.text}</h2><p className="small">{c.back.text}</p><p className="small">{c.memory?t('nextReview')+': '+formatDue(c.memory.due):t('newCard')}</p>{!c.deleted&&activeDeck(c.deckId)&&<button className="text-btn" disabled={busy} onClick={()=>void edit(c)}>{t('edit')}</button>}{controls('cards',c)}</section>)}</div>{!data.cards.some(c=>areaDecks.some(d=>d.id===c.deckId)&&matchState(c)&&(c.front.text+' '+c.back.text).toLocaleLowerCase().includes(search.toLocaleLowerCase()))&&<p className="empty">{t('noResults')}</p>}</>}
 {page==='editor'&&draft&&<Editor key={draft.id} initial={draft} library={data} t={t} onSaved={updated=>{setAreaId(updated.decks.find(d=>d.id===updated.cards.find(c=>c.id===draft.card.id)?.deckId)?.areaId??'');setData(updated);setToast(t('saved'));void store.drafts().then(setDrafts);navigate('area')}} onExit={()=>{void refresh();navigate('home')}}/>}
 {page==='explore'&&<><button className="back" onClick={()=>navigate('area')}>← {t('back')}</button>{index<explore.length?<><div className="row"><h2>{t('viewing')}</h2><span>{index+1} / {explore.length}</span></div><div className="progress"><div style={{width:`${index/explore.length*100}%`}}/></div><div className="flash"><span className="eyebrow">{t(back?'answer':'front')}</span><SideView side={cardSide(explore[index],back)} t={t}/></div>{!back?<div className="actions"><button className="good" onClick={()=>{setKnown(true);setBack(true)}}>{t('know')}</button><button className="bad" onClick={()=>{setKnown(false);setBack(true)}}>{t('dontKnow')}</button></div>:<><div className="row"><p className="small">{t('yourAnswer')}: <strong>{t(known?'know':'dontKnow')}</strong></p><button className="text-btn" disabled={busy} onClick={()=>setKnown(!known)}>{t('change')}</button></div><button className="primary wide" disabled={busy} onClick={async()=>{if(busy)return;cancelSpeech();const event={id:sessionId+':'+index,cardId:explore[index].id,at:new Date().toISOString(),known};const ok=await mutate(d=>{applyReview(d,event)});if(ok){setIndex(index+1);setBack(false)}}}>{t('next')} →</button></>}<p className="small center">{t('practiceNote')}</p></>:<div className="center"><div className="success">✓</div><h1>{t('complete')}</h1><p className="small">{t('practiceNote')}</p><button className="primary wide" onClick={()=>navigate('home')}>{t('home')}</button></div>}</>}
 {page==='settings'&&<h1>{t('settings')}</h1>}
 {page==='settings'&&<AccountPanel locale={data.preferences.locale}/>}
 {page==='settings'&&<CloudStatus t={t}/>}
 
 {page==='settings'&&<Settings key={data.revision} data={data} t={t} busy={busy} onSave={async preferences=>{if(await mutate(d=>{d.preferences=preferences}))setToast(translator(preferences.locale)('preferencesSaved'))}}/>}
 </main><nav className="bottom">{navigation}</nav>{toast&&<div className="toast" role="status">{toast}</div>}{dialog&&<Dialog title={t(dialog.kind==='purge'?'deleteForever':dialog.kind==='delete'?'confirmRemove':dialog.item?'edit':dialog.kind==='area'?'newArea':'newDeck')} closeLabel={t('cancel')} onClose={()=>{if(!busy)setDialog(null)}}>{dialog.kind==='purge'?<><p>{t(dialog.type==='areas'?'purgeAreaWarning':'purgeWarning')}</p>{dialog.type==='areas'&&<p><strong>{data.areas.find(a=>a.id===dialog.id)?.name}</strong> · {data.cards.filter(c=>data.decks.some(d=>d.areaId===dialog.id&&d.id===c.deckId)).length} {t('cards')}</p>}<button className="primary wide" disabled={busy} onClick={async()=>{setBusy(true);try{if(dialog.type==='areas')await store.purgeArea(dialog.id,data.revision);else await store.purgeCard(dialog.id,data.revision);setDialog(null);await refresh()}catch(e){setError(errorText(e,t))}finally{setBusy(false)}}}>{t('deleteForever')}</button></>:dialog.kind==='delete'?<><p>{t('recoverable')}</p><button className="primary wide" disabled={busy} onClick={async()=>{await setState(dialog.type,dialog.id,'deleted',true);setDialog(null)}}>{t('remove')}</button></>:<CollectionForm kind={dialog.kind} item={dialog.item&&dialog.kind==='area'?{...dialog.item,language:data.decks.find(d=>d.areaId===dialog.item!.id)?.language??'en-US'}:dialog.item} t={t} busy={busy} onSubmit={async(name,language)=>{const ok=await mutate(d=>{if(dialog.kind==='area'){if(dialog.item){d.areas.find(a=>a.id===dialog.item!.id)!.name=name;for(const parent of d.decks.filter(v=>v.areaId===dialog.item!.id)){parent.name=name;parent.language=language}}else{const id=crypto.randomUUID();d.areas.push({id,name,archived:false,deleted:false});d.decks.push({id:crypto.randomUUID(),areaId:id,name,language,archived:false,deleted:false})}}else if(dialog.item){const deck=d.decks.find(v=>v.id===dialog.item!.id)!;deck.name=name;deck.language=language}else d.decks.push({id:crypto.randomUUID(),areaId,name,language,archived:false,deleted:false})});if(ok)setDialog(null)}}/>}</Dialog>}</div>
}
function CollectionForm({kind,item,t,busy,onSubmit}:{kind:'area'|'deck';item?:Area|Deck;t:T;busy:boolean;onSubmit:(name:string,language:string)=>Promise<void>}){const [name,setName]=useState(item?.name??'');const [language,setLanguage]=useState(item&&'language'in item?item.language:'en-US');return <form onSubmit={e=>{e.preventDefault();if(name.trim())void onSubmit(name.trim(),language)}}><label htmlFor="collection-name">{t('name')}</label><input id="collection-name" autoFocus value={name} onChange={e=>setName(e.target.value)} required maxLength={60}/>{<><label htmlFor="collection-language">{t('language')}</label><select id="collection-language" value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></>}<button disabled={busy||!name.trim()} className="primary wide spaced">{t(busy?'saving':item?'saveSettings':'create')}</button></form>}
function Settings({data,t,busy,onSave}:{data:Library;t:T;busy:boolean;onSave:(preferences:Library['preferences'])=>Promise<void>}){const [preferences,setPreferences]=useState(data.preferences);const [error,setError]=useState('');return <><form onSubmit={e=>{e.preventDefault();try{if(!Number.isInteger(preferences.goal)||preferences.goal<1||preferences.goal>999||!Number.isInteger(preferences.newLimit)||preferences.newLimit<0||preferences.newLimit>999)throw Error();new Intl.DateTimeFormat('en',{timeZone:preferences.timezone}).format();void onSave(preferences)}catch{setError(t('invalidSettings'))}}}><div className="panel"><label htmlFor="locale">{t('uiLanguage')}</label><select id="locale" value={preferences.locale} onChange={e=>setPreferences({...preferences,locale:e.target.value as Locale})}><option value="pt">Português (Brasil)</option><option value="en">English</option><option value="es">Español</option></select><label htmlFor="goal">{t('goal')}</label><input id="goal" type="number" min={1} max={999} required value={preferences.goal} onChange={e=>setPreferences({...preferences,goal:+e.target.value})}/><label htmlFor="new-limit">{t('newLimit')}</label><input id="new-limit" type="number" min={0} max={999} required value={preferences.newLimit} onChange={e=>setPreferences({...preferences,newLimit:+e.target.value})}/><label htmlFor="timezone">{t('timezone')}</label><select id="timezone" value={preferences.timezone} onChange={e=>setPreferences({...preferences,timezone:e.target.value})}>{Array.from(new Set([preferences.timezone,...((Intl as unknown as {supportedValuesOf?:(key:string)=>string[]}).supportedValuesOf?.("timeZone")??["UTC","America/Sao_Paulo","Europe/Madrid","America/New_York"])])).sort().map(zone=><option key={zone} value={zone}>{zone.split("/").reverse().join(" · ").replaceAll("_"," ")}</option>)}</select><p className="small">{t('goalNote')}</p></div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary wide" disabled={busy}>{t('saveSettings')}</button></form></>}





