import {it,expect,vi} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import {submitAuth,authErrorKey} from './auth-actions';
function fixture(){const auth={signInWithPassword:vi.fn().mockResolvedValue({error:null}),signUp:vi.fn().mockResolvedValue({data:{session:null},error:null}),resetPasswordForEmail:vi.fn().mockResolvedValue({error:null}),updateUser:vi.fn().mockResolvedValue({error:null})};return {auth,client:{auth} as unknown as SupabaseClient}}
it('uses email signup with a same-origin confirmation redirect',async()=>{const {auth,client}=fixture();await submitAuth(client,'signup',' a@example.com ','new-password','https://brains-puce.vercel.app');expect(auth.signUp).toHaveBeenCalledWith({email:'a@example.com',password:'new-password',options:{emailRedirectTo:'https://brains-puce.vercel.app/login'}})});
it('keeps login compatible and does not trim passwords',async()=>{const {auth,client}=fixture();await submitAuth(client,'login',' a@example.com ',' pass ','https://brains-puce.vercel.app');expect(auth.signInWithPassword).toHaveBeenCalledWith({email:'a@example.com',password:' pass '})});
it('sends recovery to reset mode and updates only the authenticated password',async()=>{const {auth,client}=fixture();await submitAuth(client,'forgot','a@example.com','','https://brains-puce.vercel.app');expect(auth.resetPasswordForEmail).toHaveBeenCalledWith('a@example.com',{redirectTo:'https://brains-puce.vercel.app/login?auth=reset'});await submitAuth(client,'reset','','new-password','https://brains-puce.vercel.app');expect(auth.updateUser).toHaveBeenCalledWith({password:'new-password'})});
it('maps confirmation and rate errors without exposing raw backend details',()=>{expect(authErrorKey({code:'email_not_confirmed'})).toBe('unconfirmed');expect(authErrorKey({code:'over_email_send_rate_limit'})).toBe('rate');expect(authErrorKey({message:'private server details'})).toBe('error')});

