import {errorText,translator} from './i18n';
import {useEffect,useState} from 'react';
import {exportBackup,importBackup,type Snapshot} from './backup';
import {useStore} from './StoreContext';
import {Dialog} from './Dialog';
import type {Library} from './model';
const copy={
 pt:{title:'Backup e restauração',help:'Guarde uma cópia com cards, mídias, rascunhos e histórico. A voz de referência usa as vozes do aparelho.',save:'Baixar backup',load:'Escolher backup',confirm:'Substituir dados por este backup',warning:'Substitui a biblioteca da sua conta em todos os aparelhos. Os rascunhos deste aparelho também serão substituídos. Baixe um backup antes: não há desfazer automático.',cancel:'Cancelar',undo:'Desfazer última restauração',done:'Restauração concluída.',download:'Backup preparado. Confira o arquivo nos downloads.',error:'Não foi possível concluir. Verifique o arquivo Brains (até 100 MB), o espaço disponível e se outra aba alterou os dados.',areas:'áreas',cards:'cards',drafts:'rascunhos',working:'Processando…'},
 en:{title:'Backup and restore',help:'Keep a copy of cards, media, drafts and history. Reference speech uses device voices.',save:'Download backup',load:'Choose backup',confirm:'Replace data with this backup',warning:'Replaces your account library on all devices. Local drafts will also be replaced. Download a backup first; there is no automatic undo.',cancel:'Cancel',undo:'Undo last restore',done:'Restore complete.',download:'Backup prepared. Check your downloads.',error:'Unable to complete. Check the Brains file (up to 100 MB), available storage and whether another tab changed the data.',areas:'areas',cards:'cards',drafts:'drafts',working:'Processing…'},
 es:{title:'Copia de seguridad',help:'Guarda tarjetas, medios, borradores e historial. La voz de referencia usa las voces del dispositivo.',save:'Descargar copia',load:'Elegir copia',confirm:'Reemplazar datos con esta copia',warning:'Reemplaza la biblioteca de tu cuenta en todos los dispositivos. Los borradores locales también se reemplazan. Descarga una copia antes; no hay deshacer automático.',cancel:'Cancelar',undo:'Deshacer última restauración',done:'Restauración completada.',download:'Copia preparada. Revisa las descargas.',error:'No se pudo completar. Comprueba el archivo Brains (hasta 100 MB), el espacio y si otra pestaña cambió los datos.',areas:'áreas',cards:'tarjetas',drafts:'borradores',working:'Procesando…'}
};
export function Backup({data,onRestored}:{data:Library;onRestored:()=>Promise<void>}){
 const store=useStore();
 const t=copy[data.preferences.locale];const [pending,setPending]=useState<Snapshot|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[recovery,setRecovery]=useState(false);
 useEffect(()=>{let active=true;void store.hasRecovery().then(v=>{if(active)setRecovery(v)}).catch(()=>{});return()=>{active=false}},[data.revision]);
 async function restore(value:Snapshot|null){setBusy(true);try{await store.restore(value,data.revision);setPending(null);await onRestored();setMessage(t.done);setRecovery(false)}catch(e){await onRestored();setMessage(e instanceof Error&&e.message==='draftRestoreFailed'?errorText(e,translator(data.preferences.locale)):t.error)}finally{setBusy(false)}}
 return <section className="panel spaced"><h2>{t.title}</h2><p className="small">{t.help}</p><div className="area-actions"><button type="button" className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const blob=await exportBackup(await store.snapshot());const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`brains-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setMessage(t.download)}catch{setMessage(t.error)}finally{setBusy(false)}}}>{t.save}</button></div><label htmlFor="backup-file">{t.load}</label><input id="backup-file" type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);try{setPending(await importBackup(file));setMessage('')}catch{setMessage(t.error)}finally{setBusy(false)}}}/>{recovery&&<button type="button" className="text-btn" disabled={busy} onClick={()=>void restore(null)}>{t.undo}</button>}<p role="status">{busy?t.working:message}</p>{pending&&<Dialog title={t.title} closeLabel={t.cancel} onClose={()=>{if(!busy)setPending(null)}}><p>{pending.library.areas.length} {t.areas} · {pending.library.cards.length} {t.cards} · {pending.drafts.length} {t.drafts}</p><p>{t.warning}</p><button className="primary wide" disabled={busy} onClick={()=>void restore(pending)}>{t.confirm}</button></Dialog>}</section>
}

