import {cardSide,sharedCard} from './review';
import {useEffect,useRef,useState} from 'react';
import {normalize,validateCard,type Card,type Draft,type Library} from './model';
import {useStore} from './StoreContext';
import {errorText,type T} from './i18n';
import {SideEditor,SideView} from './Media';
import {Dialog} from './Dialog';
export function Editor({initial,library,t,onSaved,onExit}:{initial:Draft;library:Library;t:T;onSaved:(data:Library)=>void;onExit:()=>void}){
 const store=useStore();
 const [card,setCard]=useState<Card>(()=>sharedCard({...initial.card,front:{...initial.card.front,audioText:'',language:library.decks.find(d=>d.id===initial.card.deckId)?.language??initial.card.front.language}}));const latest=useRef(card);latest.current=card;const draft=useRef(initial);const queue=useRef(Promise.resolve());const [status,setStatus]=useState('draftSaved');const [error,setError]=useState('');const [busySides,setBusySides]=useState({front:false,back:false});const [saving,setSaving]=useState(false);const [dialog,setDialog]=useState<'duplicate'|'preview'|'leave'|'discard'|null>(null);const [previewBack,setPreviewBack]=useState(false);const alive=useRef(true);const timer=useRef<ReturnType<typeof setTimeout> | undefined>(undefined);const dirty=useRef(false);const busy=busySides.front||busySides.back;
 function persist(value:Card){queue.current=queue.current.catch(()=>{}).then(async()=>{try{const saved=await store.saveDraft({...draft.current,card:value});draft.current=saved;if(alive.current&&latest.current===value){dirty.current=false;setStatus('draftSaved');setError('')}}catch(e){if(alive.current){setStatus('draftError');setError(errorText(e,t))}throw e}});return queue.current}
 function update(value:Card){latest.current=value;dirty.current=true;setCard(value);setStatus('draftWaiting');clearTimeout(timer.current);timer.current=setTimeout(()=>{void persist(value).catch(()=>{})},300)}
 useEffect(()=>{alive.current=true;const unload=(e:BeforeUnloadEvent)=>{if(dirty.current||busy||saving){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('beforeunload',unload)}},[busy,saving]);
 useEffect(()=>()=>{alive.current=false;clearTimeout(timer.current)},[]);
 async function save(allowDuplicate=false){if(busy||saving)return;setError('');try{validateCard(card,library);const mismatch=[card.front].some(s=>(s.audio||s.audioPath)&&['recording','file'].includes(s.mode)&&s.recordedFor!==undefined&&s.recordedFor!==(s.audioText||s.text));if(mismatch){setError(t('changedAudio'));return}if(!allowDuplicate&&library.cards.some(c=>c.id!==card.id&&!c.deleted&&c.deckId===card.deckId&&normalize(c.front.text)===normalize(card.front.text))){setDialog('duplicate');return}setSaving(true);setDialog(null);clearTimeout(timer.current);await persist(card);const data=await store.saveCard(card,initial.baseVersion,draft.current);dirty.current=false;onSaved(data)}catch(e){setError(errorText(e,t))}finally{if(alive.current)setSaving(false)}}
 async function leave(){if(busy)return;setSaving(true);try{clearTimeout(timer.current);await persist(card);onExit()}catch(e){setError(errorText(e,t));setDialog(null)}finally{if(alive.current)setSaving(false)}}
 async function discard(){setSaving(true);try{clearTimeout(timer.current);await queue.current.catch(()=>{});await store.removeDraft(draft.current.id,draft.current.revision);dirty.current=false;onExit()}catch(e){setError(errorText(e,t));setDialog(null)}finally{if(alive.current)setSaving(false)}}
 return <><button className="back" disabled={busy||saving} onClick={()=>setDialog('leave')}>← {t('back')}</button><h1>{t(initial.baseVersion?'edit':'add')}</h1><p className="small" role="status">{t(status as 'draftSaved'|'draftWaiting'|'draftError')}</p><form onSubmit={e=>{e.preventDefault();void save()}}><label htmlFor="deck">{t('chooseDeck')}</label><select id="deck" disabled={busy||saving} value={card.deckId} onChange={e=>update({...card,deckId:e.target.value,front:{...card.front,audioText:'',language:library.decks.find(d=>d.id===e.target.value)!.language}})}>{library.decks.filter(d=>!d.archived&&!d.deleted&&library.areas.some(a=>a.id===d.areaId&&!a.deleted&&!a.archived)&&library.decks.find(v=>v.areaId===d.areaId)?.id===d.id).map(d=><option value={d.id} key={d.id}>{library.areas.find(a=>a.id===d.areaId)?.name}</option>)}</select><fieldset disabled={saving}><div className="card-editor-sides"><SideEditor side={card.front} id="front" t={t} onChange={value=>update({...latest.current,front:value})} onBusy={value=>setBusySides(old=>({...old,front:value}))}/><SideEditor side={card.back} id="back" t={t} onChange={value=>update({...latest.current,back:value})} onBusy={value=>setBusySides(old=>({...old,back:value}))}/></div></fieldset><p className="small">{t('noAssessment')}</p>{error&&<p role="alert" className="error">{error}</p>}<div className="actions"><button type="button" className="secondary" disabled={busy||saving} onClick={()=>{setPreviewBack(false);setDialog('preview')}}>{t('preview')}</button><button className="primary" disabled={busy||saving} type="submit">{t(saving?'saving':'save')} →</button></div><button className="text-btn danger spaced" type="button" disabled={busy||saving} onClick={()=>setDialog('discard')}>{t('discard')}</button></form>
 {dialog&&<Dialog title={t(dialog==='duplicate'?'duplicate':dialog==='preview'?'previewCard':dialog==='discard'?'confirmDiscard':'leaveTitle')} closeLabel={t('cancel')} onClose={()=>{if(!saving)setDialog(null)}}>{dialog==='preview'?<><div className="flash"><span className="eyebrow">{t(previewBack?'answer':'front')}</span><SideView side={cardSide(card,previewBack)} t={t}/></div><button className="primary wide" onClick={()=>setPreviewBack(!previewBack)}>{t(previewBack?'front':'reveal')}</button></>:dialog==='duplicate'?<div className="actions spaced"><button className="secondary" onClick={()=>setDialog(null)}>{t('cancel')}</button><button className="primary" onClick={()=>void save(true)}>{t('saveAnyway')}</button></div>:<><p>{t(dialog==='discard'?'discardHelp':'leaveHelp')}</p><button className="primary wide" disabled={saving} onClick={()=>void(dialog==='discard'?discard():leave())}>{t(saving?'saving':dialog==='discard'?'discard':'saveDraft')}</button><button className="text-btn" disabled={saving} onClick={()=>setDialog(null)}>{t('continue')}</button></>}</Dialog>}</>
}

