import {useBlocker} from 'react-router-dom';
import {cardSide,sharedCard} from './review';
import {useEffect,useRef,useState} from 'react';
import {normalize,validateCard,type Card,type Draft,type Library} from './model';
import {useStore} from './StoreContext';
import {errorText,type T} from './i18n';
import {SideEditor,SideView} from './Media';
import {Dialog} from './Dialog';
import {cloud} from './cloud';
import {optimizeImage} from './image-compression';
export function Editor({initial,library,t,onSaved,onExit}:{initial:Draft;library:Library;t:T;onSaved:(data:Library)=>void;onExit:()=>void}){
 const store=useStore();
 const [card,setCard]=useState<Card>(()=>sharedCard({...initial.card,front:{...initial.card.front,audioText:'',language:library.decks.find(d=>d.id===initial.card.deckId)?.language??initial.card.front.language}}));const latest=useRef(card);latest.current=card;const draft=useRef(initial);const queue=useRef(Promise.resolve());const [status,setStatus]=useState('draftSaved');const [error,setError]=useState('');const [busySides,setBusySides]=useState({front:false,back:false});const [saving,setSaving]=useState(false);const [dialog,setDialog]=useState<'duplicate'|'preview'|'leave'|'discard'|null>(null);const [previewBack,setPreviewBack]=useState(false);const alive=useRef(true);const timer=useRef<ReturnType<typeof setTimeout> | undefined>(undefined);const dirty=useRef(false);const [aiBusy,setAiBusy]=useState<'sentence'|'image'|null>(null);const [remaining,setRemaining]=useState({sentence:3,image:3});const aiEnabled=import.meta.env.VITE_AI_ENABLED==='true';const busy=busySides.front||busySides.back||!!aiBusy;
 useEffect(()=>{if(!aiEnabled||!cloud)return;let active=true;void cloud.rpc('ai_generation_remaining',{p_card_id:card.id}).then(({data,error})=>{if(active&&!error&&data)setRemaining(data)});return()=>{active=false}},[card.id,aiEnabled]);
 async function generate(kind:'sentence'|'image'){
  if(!aiEnabled||!cloud||busy||saving||!card.front.text.trim()||remaining[kind]<=0)return;
  setAiBusy(kind);setError('');
  try{
   const session=await cloud.auth.getSession();const token=session.data.session?.access_token;if(!token)throw Error('authenticationRequired');
   const vocabulary=Array.from(new Set(library.cards.filter(c=>c.id!==card.id&&c.deckId===card.deckId&&!c.deleted&&!c.archived).sort((a,b)=>(b.memory?.reps??0)-(a.memory?.reps??0)).map(c=>c.front.text.trim()).filter(v=>v&&v.length<=80))).slice(0,40);
   const response=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({cardId:card.id,kind,front:card.front.text,back:card.back.text,language:card.front.language,vocabulary})});
   const result=await response.json();if(!response.ok)throw Error(result.error==='limit'?'aiLimit':result.error==='providerLimit'?'aiProviderLimit':result.error==='unavailable'?'aiUnavailable':result.error==='authentication'?'authenticationRequired':'aiFailed');
   if(kind==='sentence'){if(typeof result.sentence!=='string')throw Error('aiFailed');update({...latest.current,back:{...latest.current.back,text:result.sentence}})}
   else{if(typeof result.image!=='string'||result.image.length>8_000_000||result.mime!=='image/jpeg')throw Error('aiFailed');const bytes=Uint8Array.from(atob(result.image),c=>c.charCodeAt(0));const optimized=await optimizeImage(new File([bytes],'brains-ai.jpg',{type:'image/jpeg'}));update({...latest.current,back:{...latest.current.back,image:optimized,imagePath:undefined,imagePending:undefined}})}
   setRemaining(old=>({...old,[kind]:Number(result.remaining)}));
  }catch(e){setError(errorText(e,t))}finally{setAiBusy(null)}
 }
 const allowNavigation=useRef(false);
 const blocker=useBlocker(()=>!allowNavigation.current);
 useEffect(()=>{if(blocker.state==='blocked')setDialog('leave')},[blocker.state]);
 function closeDialog(){if(saving)return;if(blocker.state==='blocked')blocker.reset();setDialog(null)}
 function exit(){allowNavigation.current=true;if(blocker.state==='blocked')blocker.proceed();else onExit()}
 function persist(value:Card){queue.current=queue.current.catch(()=>{}).then(async()=>{try{const saved=await store.saveDraft({...draft.current,card:value});draft.current=saved;if(alive.current&&latest.current===value){dirty.current=false;setStatus('draftSaved');setError('')}}catch(e){if(alive.current){setStatus('draftError');setError(errorText(e,t))}throw e}});return queue.current}
 function update(value:Card){latest.current=value;dirty.current=true;setCard(value);setStatus('draftWaiting');clearTimeout(timer.current);timer.current=setTimeout(()=>{void persist(value).catch(()=>{})},300)}
 useEffect(()=>{alive.current=true;const unload=(e:BeforeUnloadEvent)=>{if(dirty.current||busy||saving){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('beforeunload',unload)}},[busy,saving]);
 useEffect(()=>()=>{alive.current=false;clearTimeout(timer.current)},[]);
 async function save(allowDuplicate=false){if(busy||saving)return;setError('');try{validateCard(card,library);const mismatch=[card.front,card.back].some(s=>(s.audio||s.audioPath)&&['recording','file'].includes(s.mode)&&s.recordedFor!==undefined&&s.recordedFor!==(s.audioText||s.text));if(mismatch){setError(t('changedAudio'));return}if(!allowDuplicate&&library.cards.some(c=>c.id!==card.id&&!c.deleted&&c.deckId===card.deckId&&normalize(c.front.text)===normalize(card.front.text))){setDialog('duplicate');return}setSaving(true);setDialog(null);clearTimeout(timer.current);await persist(card);const data=await store.saveCard(card,initial.baseVersion,draft.current);dirty.current=false;allowNavigation.current=true;onSaved(data)}catch(e){setError(errorText(e,t))}finally{if(alive.current)setSaving(false)}}
 async function leave(){if(busy)return;setSaving(true);try{clearTimeout(timer.current);if(dirty.current)await persist(card);await queue.current;exit()}catch(e){setError(errorText(e,t));setDialog(null)}finally{if(alive.current)setSaving(false)}}
 async function discard(){setSaving(true);try{clearTimeout(timer.current);await queue.current.catch(()=>{});if(draft.current.revision>0)await store.removeDraft(draft.current.id,draft.current.revision);dirty.current=false;exit()}catch(e){setError(errorText(e,t));setDialog(null)}finally{if(alive.current)setSaving(false)}}
 return <><button className="back" disabled={busy||saving} onClick={()=>setDialog('leave')}>← {t('back')}</button><h1>{t(initial.baseVersion?'editCard':'add')}</h1>{draft.current.revision>0||dirty.current?<p className="small" role="status">{t(status as 'draftSaved'|'draftWaiting'|'draftError')}</p>:null}<form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={saving||!!aiBusy}><div className="card-editor-sides"><fieldset disabled={busySides.back}><SideEditor side={card.front} id="front" t={t} onChange={value=>update({...latest.current,front:value})} onBusy={value=>setBusySides(old=>({...old,front:value}))}/></fieldset><fieldset disabled={busySides.front}><SideEditor side={card.back} id="back" t={t} ai={aiEnabled?{front:card.front.text,remaining,busy:aiBusy,onGenerate:generate}:undefined} onChange={value=>update({...latest.current,back:value})} onBusy={value=>setBusySides(old=>({...old,back:value}))}/></fieldset></div></fieldset>{error&&<p role="alert" className="error">{error}</p>}<div className="actions"><button type="button" className="secondary" disabled={busy||saving} onClick={()=>{setPreviewBack(false);setDialog('preview')}}>{t('preview')}</button><button className="primary" disabled={busy||saving} type="submit">{t(saving?'saving':'save')} →</button></div><button className="text-btn danger spaced" type="button" disabled={busy||saving} onClick={()=>setDialog('discard')}>{t('discard')}</button></form>
 {dialog&&<Dialog title={t(dialog==='duplicate'?'duplicate':dialog==='preview'?'previewCard':dialog==='discard'?'confirmDiscard':'leaveTitle')} closeLabel={t('cancel')} onClose={closeDialog}>{dialog==='preview'?<><div className="flash"><span className="eyebrow">{t(previewBack?'answer':'front')}</span><SideView key={String(previewBack)} side={cardSide(card,previewBack)} t={t} automatic={previewBack} showPronunciation={!previewBack}/></div><button className="primary wide" onClick={()=>setPreviewBack(!previewBack)}>{t(previewBack?'front':'reveal')}</button></>:dialog==='duplicate'?<div className="actions spaced"><button className="secondary" onClick={()=>setDialog(null)}>{t('cancel')}</button><button className="primary" onClick={()=>void save(true)}>{t('saveAnyway')}</button></div>:<><p>{t(dialog==='discard'?'discardHelp':'leaveHelp')}</p><button className="primary wide" disabled={saving} onClick={()=>void(dialog==='discard'?discard():leave())}>{t(saving?'saving':dialog==='discard'?'discard':'saveDraft')}</button><button className="text-btn" disabled={saving} onClick={closeDialog}>{t('continue')}</button></>}</Dialog>}</>
}

