import 'fake-indexeddb/auto';
import {describe,it,expect} from 'vitest';
import {LocalStore} from './storage';
import {blankCard,type Draft} from './model';
async function setup(){const store=new LocalStore(crypto.randomUUID());const data=await store.mutate(0,d=>{d.areas.push({id:'a',name:'English',archived:false,deleted:false});d.decks.push({id:'d',areaId:'a',name:'General',language:'en-US',archived:false,deleted:false})});const card=blankCard(data.decks[0]);card.front.text='Hello';card.back.text='Olá';const draft=await store.saveDraft({id:'draft',card,baseVersion:0,revision:0,savedAt:''});return {store,data,card,draft}}
describe('local content integrity',()=>{
 it('persists card and blobs atomically, removes draft only on success',async()=>{const {store,card,draft}=await setup();card.front.image=new Blob(['picture'],{type:'image/png'});card.front.mode='recording';card.front.audio=new Blob(['sound'],{type:'audio/webm'});await store.saveCard(card,0,draft);await store.close();const saved=await store.read();expect(await saved.cards[0].front.audio!.text()).toBe('sound');expect(await saved.cards[0].front.image!.text()).toBe('picture');expect(await store.drafts()).toHaveLength(0);expect(saved.cards[0].version).toBe(1);await store.close()});
 it('keeps draft and existing library if validation fails',async()=>{const {store,card,draft}=await setup();card.back.text='';await expect(store.saveCard(card,0,draft)).rejects.toThrow('required');expect((await store.read()).cards).toHaveLength(0);expect(await store.drafts()).toHaveLength(1);await store.close()});
 it('rejects stale library updates from another tab',async()=>{const {store,data}=await setup();await store.mutate(data.revision,d=>{d.areas[0].name='Changed'});await expect(store.mutate(data.revision,d=>{d.areas=[]})).rejects.toThrow('conflict');expect((await store.read()).areas[0].name).toBe('Changed');await store.close()});
 it('prevents stale drafts from overwriting newer text',async()=>{const {store,draft}=await setup();const newer=await store.saveDraft({...draft,card:{...draft.card,front:{...draft.card.front,text:'New'}}});await expect(store.saveDraft(draft)).rejects.toThrow('draftConflict');expect((await store.drafts())[0].revision).toBe(newer.revision);await store.close()});
 it('rejects concurrent card edits and retains losing draft',async()=>{const {store,card,draft}=await setup();await store.saveCard(card,0,draft);const c=(await store.read()).cards[0];const d1=await store.saveDraft({id:'one',card:c,baseVersion:1,revision:0,savedAt:''});const d2=await store.saveDraft({id:'two',card:c,baseVersion:1,revision:0,savedAt:''});await store.saveCard({...c,front:{...c.front,text:'Winner'}},1,d1);await expect(store.saveCard(c,1,d2)).rejects.toThrow('conflict');expect((await store.read()).cards[0].front.text).toBe('Winner');expect((await store.drafts())[0].id).toBe('two');await store.close()});
 it('rolls back a failed transaction without modifying data',async()=>{const {store,data}=await setup();await expect(store.mutate(data.revision,d=>{d.areas=[];throw Error('forced failure')})).rejects.toThrow('forced failure');expect((await store.read()).areas).toHaveLength(1);await store.close()});
 it('prevents saving into archived parent and leaves draft recoverable',async()=>{const {store,data,card,draft}=await setup();await store.mutate(data.revision,d=>{d.areas[0].archived=true});await expect(store.saveCard(card,0,draft)).rejects.toThrow('missingDeck');expect(await store.drafts()).toHaveLength(1);await store.close()});
});
