import {flattenAreas} from './areas';
import {initialLibrary,validateCard,type Library,type Draft,type Card} from './model';
export class LocalStore {
 private connection?:Promise<IDBDatabase>;
 get databaseName(){return this.name}
 constructor(private name='personal-anki-library-v1'){}
 private open(){return this.connection??=new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(this.name,1);request.onupgradeneeded=()=>{request.result.createObjectStore('library');request.result.createObjectStore('drafts',{keyPath:'id'})};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error('blocked'));request.onsuccess=()=>{request.result.onversionchange=()=>{request.result.close();this.connection=undefined};resolve(request.result)}})}
 async read():Promise<Library>{const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction(['library','drafts'],'readwrite');let result:Library;const req=tx.objectStore('library').get('main');req.onsuccess=()=>{result=req.result??initialLibrary();const dr=tx.objectStore('drafts').getAll();dr.onsuccess=()=>{if(flattenAreas(result,dr.result)){tx.objectStore('library').put(result,'main');for(const draft of dr.result)tx.objectStore('drafts').put(draft)}}};tx.oncomplete=()=>resolve(result);tx.onabort=()=>reject(tx.error??Error('storageError'));tx.onerror=()=>{}})}
 async drafts():Promise<Draft[]>{const db=await this.open();return new Promise((resolve,reject)=>{const req=db.transaction('drafts').objectStore('drafts').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
 async mutate(expectedRevision:number,change:(data:Library)=>void):Promise<Library>{const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('library','readwrite');let result:Library;let error:unknown;const req=tx.objectStore('library').get('main');req.onsuccess=()=>{try{result=req.result??initialLibrary();if(result.revision!==expectedRevision)throw Error('conflict');change(result);result.revision++;tx.objectStore('library').put(result,'main')}catch(e){error=e;tx.abort()}};tx.oncomplete=()=>resolve(result);tx.onabort=()=>reject(error??tx.error??Error('storageError'));tx.onerror=()=>{}})}
 async saveDraft(draft:Draft):Promise<Draft>{const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');const store=tx.objectStore('drafts');let result:Draft;let error:unknown;const req=store.get(draft.id);req.onsuccess=()=>{const old=req.result as Draft|undefined;if(old&&old.revision!==draft.revision){error=Error('draftConflict');tx.abort();return}result={...draft,revision:draft.revision+1,savedAt:new Date().toISOString()};store.put(result)};tx.oncomplete=()=>resolve(result);tx.onabort=()=>reject(error??tx.error??Error('storageError'));tx.onerror=()=>{}})}
 async replaceDrafts(values:Draft[]){const db=await this.open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');const st=tx.objectStore('drafts');st.clear();for(const value of values)st.put(value);tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error??Error('storageError'))})}
 async removeDraft(id:string,revision:number){const db=await this.open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');const st=tx.objectStore('drafts');let conflict=false;const req=st.get(id);req.onsuccess=()=>{if(req.result&&req.result.revision!==revision){conflict=true;tx.abort()}else st.delete(id)};tx.oncomplete=()=>resolve();tx.onabort=()=>reject(Error(conflict?'draftConflict':'storageError'));tx.onerror=()=>{}})}
 async saveCard(card:Card,baseVersion:number,draft:Draft):Promise<Library>{const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction(['library','drafts'],'readwrite');const st=tx.objectStore('library');let result:Library;let error:unknown;const req=st.get('main');req.onsuccess=()=>{try{result=req.result??initialLibrary();validateCard(card,result);const old=result.cards.find(c=>c.id===card.id);if((old?.version??0)!==baseVersion||old?.deleted)throw Error('conflict');const dr=tx.objectStore('drafts').get(draft.id);dr.onsuccess=()=>{try{if(dr.result&&dr.result.revision!==draft.revision)throw Error('draftConflict');const saved={...card,version:baseVersion+1,updatedAt:new Date().toISOString()};result.cards=result.cards.filter(c=>c.id!==card.id).concat(saved);result.revision++;st.put(result,'main');tx.objectStore('drafts').delete(draft.id)}catch(e){error=e;tx.abort()}}}catch(e){error=e;tx.abort()}};tx.oncomplete=()=>resolve(result);tx.onabort=()=>reject(error??tx.error??Error('storageError'));tx.onerror=()=>{}})}
 async snapshot():Promise<import('./backup').Snapshot>{const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction(['library','drafts'],'readonly');const l=tx.objectStore('library').get('main');const d=tx.objectStore('drafts').getAll();tx.oncomplete=()=>resolve({library:l.result??initialLibrary(),drafts:d.result});tx.onabort=()=>reject(tx.error)})}
 async restore(snapshot:import('./backup').Snapshot|null,expectedRevision:number){const db=await this.open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(['library','drafts'],'readwrite');const lib=tx.objectStore('library'),drafts=tx.objectStore('drafts');const current=lib.get('main'),all=drafts.getAll(),recovery=lib.get('recovery');let error:unknown;recovery.onsuccess=()=>{try{const old=current.result??initialLibrary();if(old.revision!==expectedRevision)throw Error('conflict');const next=structuredClone(snapshot??recovery.result);if(!next)throw Error('storageError');lib.put({library:old,drafts:all.result},'recovery');next.library.revision=old.revision+1;for(const c of next.library.cards)c.version=Math.max(c.version,old.cards.find((v:Card)=>v.id===c.id)?.version??0)+1;for(const d of next.drafts){d.baseVersion=next.library.cards.find((c:Card)=>c.id===d.card.id)?.version??0;d.revision++}lib.put(next.library,'main');drafts.clear();for(const d of next.drafts)drafts.put(d)}catch(e){error=e;tx.abort()}};tx.oncomplete=()=>resolve();tx.onabort=()=>reject(error??tx.error)})}
 async hasRecovery(){const db=await this.open();return new Promise<boolean>((resolve,reject)=>{const req=db.transaction('library').objectStore('library').get('recovery');req.onsuccess=()=>resolve(!!req.result);req.onerror=()=>reject(req.error)})}
 async purgeCard(id:string,expectedRevision:number){const db=await this.open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(['library','drafts'],'readwrite');const lib=tx.objectStore('library'),drafts=tx.objectStore('drafts');const current=lib.get('main'),all=drafts.getAll(),recovery=lib.get('recovery');let error:unknown;recovery.onsuccess=()=>{try{const data=current.result as Library;if(!data||data.revision!==expectedRevision)throw Error('conflict');if(!data.cards.some(c=>c.id===id&&c.deleted))throw Error('conflict');const strip=(d:Library)=>{d.cards=d.cards.filter(c=>c.id!==id);d.reviews=d.reviews?.filter(e=>e.cardId!==id)};strip(data);data.revision++;lib.put(data,'main');for(const draft of all.result as Draft[])if(draft.card.id===id)drafts.delete(draft.id);if(recovery.result){const old=recovery.result;strip(old.library);old.drafts=old.drafts.filter((d:Draft)=>d.card.id!==id);lib.put(old,'recovery')}}catch(e){error=e;tx.abort()}};tx.oncomplete=()=>resolve();tx.onabort=()=>reject(error??tx.error)})}
 async syncBase():Promise<import('./sync-plan').SyncRecord[]>{const db=await this.open();return new Promise((resolve,reject)=>{const req=db.transaction('library').objectStore('library').get('syncBase');req.onsuccess=()=>resolve(req.result??[]);req.onerror=()=>reject(req.error)})}
 async commitSynced(library:Library,base:import('./sync-plan').SyncRecord[],expectedRevision:number){const db=await this.open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('library','readwrite');const st=tx.objectStore('library'),req=st.get('main');let error:unknown;req.onsuccess=()=>{const old=req.result??initialLibrary();if(old.revision!==expectedRevision){error=Error('conflict');tx.abort();return}st.put({...library,revision:old.revision+1},'main');st.put(base,'syncBase')};tx.oncomplete=()=>resolve();tx.onabort=()=>reject(error??tx.error)})}
 async owner():Promise<string|undefined>{const db=await this.open();return new Promise((resolve,reject)=>{const req=db.transaction('library').objectStore('library').get('owner');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
 async bindOwner(userId:string){if(!userId.trim())throw Error('invalidOwner');const db=await this.open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('library','readwrite');const st=tx.objectStore('library');const req=st.get('owner');let error:unknown;req.onsuccess=()=>{if(req.result&&req.result!==userId){error=Error('ownerMismatch');tx.abort()}else st.put(userId,'owner')};tx.oncomplete=()=>resolve();tx.onabort=()=>reject(error??tx.error)})}
 async uploads():Promise<import('./cloud-store').UploadTask[]>{const db=await this.open();return new Promise((resolve,reject)=>{const req=db.transaction('library').objectStore('library').getAll();req.onsuccess=()=>resolve(req.result.filter(v=>v?.uploadTask).map(v=>v.uploadTask));req.onerror=()=>reject(req.error)})}
 async putUpload(task:import('./cloud-store').UploadTask){const db=await this.open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('library','readwrite');tx.objectStore('library').put({uploadTask:task},'upload:'+task.id);tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error)})}
 async removeUpload(id:string){const db=await this.open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('library','readwrite');tx.objectStore('library').delete('upload:'+id);tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error)})}
 async close(){(await this.open()).close();this.connection=undefined}
}
export function accountDatabaseName(userId:string){if(!userId.trim())throw Error('accountRequired');return 'brains-account-v1-'+encodeURIComponent(userId)}
